version: '1'
services:
  countries-microservicio:
    image: countries-app
    build: .
    ports:
      - "8080:8080"
    environment:
      APP_NAME: countries-microservicio
      EXTERNAL_API_URL: http://countries-api:8080